### ISSUE TITLE
What file to use at OSHPark and Part Number of SMA Adaptor

### ISSUE THREAD

**Issue by bootsy52** [nebkat/xbee-smd-tht-adapter-board-reference-design#1]
Sorry I found no other way contacting you than this one.

I was really excited when I found your project as this is exactly what I need as this Chip only comes in SMD. Astonishing work.

Now I want to create a PCB, OSHPark https://oshpark.com/ accepts kicad files so is it sufficient to just submit xbee-smd-tht.kicad_pcb? Or which PCB manufacturer do you use?

Second do you have some (Mouser, Digi Key) Part Numbers for the RPSMA Adapter which is used? I assume that the pin headers are just regular ones, right?

Thanx so much for your work

**Comment by nebkat** [comment]
Hi @bootsy52,

Personally I use JLCPCB but you would have to export gerbers in KiCAD for them. OSHPark will indeed accept the kicad_pcb file.

The SMA part is a Linx CONSMA003.062, though there may be other parts that fit the dimensions too, it seems to be a common design.

Good luck with your build!

**Comment by bootsy52** [comment]
@nebkat 

Thanx for your information, once you get an initial Part number you'll find more because then you know what the name of it is you're searching for :-)

Seems that the RP-SMA Variant are Linx CONREVSMA003.031 and CONREVSMA003.062 are other alternatives, however I did not find many other parts from other manufactures which have the pin on the same height as the outter terminals, so the part number was a valuable information :-)

Another thing comes to mind, have you ever thought about adding screw holes to the PCB? This could be handy if you want to fixate the PCB using self adhesive distance spacers or fixiate the PCB with screws.

**Comment by nebkat** [comment]
@bootsy52 

What SMD module are you making your boards for?

The through hole pins seem to hold the board in very well so I haven't found a need for any screws, and there's also not much space available for holes, but you could add it to the board for your application if needed.

**Comment by bootsy52** [comment]
@nebkat I have yet to decide which module to use, however I need (as I am in Europe) the Xbee SX868 Variant. I thought about this one

XB8-DMPS-002

[https://www.digikey.com/product-detail/en/digi-international/XB8-DMPS-002/602-1820-ND/3482640](https://www.digikey.com/product-detail/en/digi-international/XB8-DMPS-002/602-1820-ND/3482640)

Would that work?

That with the screw holes was just an idea, as we have to put this together with a Raspberry Pi in a larger case

**Comment by nebkat** [comment]
@bootsy52 
I used the XB8X-DMRS-001, I think that should be fine too. Are your antennas SMA or RP-SMA? I think the 868MHz antennas are normally SMA.

**Comment by bootsy52** [comment]
@nebkat Damn, you're so right. All Antennas are RP-SMA but the 868 ones are SMA, I just checked my inventory.

**Comment by bootsy52** [comment]
@nebkat Sorry, I do not have an E-Mail Address of you. So I wanted to ask if you also do paid custom work?

Actually I need the exact same thing like this for the **AI Thinker RHF76-052** module, it seems there is a similar library to RHF06-052 as a starting point for KiCad

https://github.com/KiCad/kicad-footprints/blob/master/RF_Module.pretty/Ai-Thinker-Ra-01-LoRa.kicad_mod

and for RHF76-052 this in EasyEDA

https://easyeda.com/components/RHF76-052_b0dab0d5c2da4aac9bc3f4e83182a5d4

Are you able to write an invoice? You could publish this work as OpenSource on GitHub if you like as for me it is just relevant to get a solution for development, I'm not in a hurry as I've got other projects right now. 

If you like you can contact me at: cm <at> p-i-u.de (Spam protected :-)
